# the dev keys use the amazon sandbox account for dev@reliefhub.org
development: &sandbox
  access_key: AKIAJT3POPIBST76SUJQ
  amazon_payments_account_id: BFEWRUXTBLRP72PUVPNDRTTXELVXHN85VDMES8
  
# staging and production use heroku environment variables  
staging: &default
  access_key: ENV['AMAZON_FPS_ACCESS_KEY']
  amazon_payments_account_id: ENV['AMAZON_PAYMENTS_ACCOUNT_ID']

producton:
  <<: *default

test:
  access_key: TEST_ACCESS_KEY
  amazon_payments_account_id: TEST_ACCOUNT_ID
