development: &default
  adapter: postgresql
  username: postgres
  password: postgres
  min_messages: warning
  # adapter: mysql
  # username: root
  # password: 
  database: reliefhub_development
  host: localhost
  encoding: utf8

test: &test
  <<: *default
  database: reliefhub_test

cucumber:
  <<: *test
