staging: &default
  access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: 'reliefhub_staging'

production:
  <<: *default
  bucket: 'reliefhub_production'
